#
###################################
# Site wide configuration
####################################
#
title: DevTales | Umang Galaiya
email: umang@umanggalaiya.in
description: Tales from my everyday life as a Software Engineer
url: https://devtales.umanggalaiya.in # the base hostname & protocol for your site
keywords: ["Programming", "Software Engineer", "Software Engineering", "Technology", "Umang", "Galaiya", "Tech"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Kolkata
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Umang Galaiya
  avatar: 
  job: "Full-Stack Web Developer"
  bio: "A full-stack web dev, expirementing with tech and software engineering."
  email: umang@umanggalaiya.in
  disqus-shortname: umanghome
  twitter: umanghome #username
  facebook: umanghome #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: umanghome #username
  stackoverflow: 4176188/umang-galaiya #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: umanggalaiya #username
  xing: #username
  instagram: umanghome #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
