#
###################################
# Site wide configuration
####################################
#
title: Blog | Umang Galaiya
email: umang@umanggalaiya.in
description: Musings from my everyday life as a Software Engineer
url: https://umanggalaiya.in/blog # the base hostname & protocol for your site
keywords: ["Programming", "Software Engineer", "Software Engineering", "Software", "Engineering", "Engineer", "Code", "Technology", "Umang", "Galaiya", "Tech", "Technology", "Blog"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Kolkata
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /:year/:title.html

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Umang Galaiya
  avatar: umang.jpg
  job: "CS person acting as a Software Dev"
  bio: "Tech nerd, tinkerer, reader."
  email: umang@umanggalaiya.in
  disqus-shortname: umanggalaiyablog
  twitter: umanghome #username
  facebook: umanghome #username
  google:
    plus:
    analytics: UA-58535571-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: umanghome #username
  stackoverflow: 4176188/umang-galaiya #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: umanggalaiya #username
  xing: #username
  instagram: umanghome #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
